name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Check out the repo
        uses: actions/checkout@v2

      # Paso 2: Configurar Node.js (versión 18)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Cambia a la versión 18

      # Paso 3: Instalar dependencias de Node.js
      - name: Install dependencies
        run: npm install

      # Paso 4: Construir el sitio con npm run build
      - name: Build the site
        run: npm run build

      # Paso 5: Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Directorio de salida del sitio estático

